# Run Monica with a supervisor process
#
# You might want to set these variables in you .env file:
#
#- APP_ENV=production
#- APP_URL with your domain (https scheme)
#- APP_KEY with a random string
#
#- DB_HOST=db
# See `db` container for these values:
#- DB_DATABASE=monica
#- DB_USERNAME=monica
#- DB_PASSWORD=secret
#

version: "3.9"

services:
  app:
    build: ./app
    image: monica-app
    depends_on:
      - db
    env_file: .env
    ports:
      - 80:80
    volumes:
      - data:/var/www/html/storage
    restart: always

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always


volumes:
  data:
    driver: local
  mysqldata:
    driver: local
